version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/apps/rosata-cn"
      - "/apps/obsidian-kb"
      - "/packages/theme"
    schedule:
      interval: "daily"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
    pull-request-branch-name:
      separator: "-"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
